config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "users#index"

  # resources :statements do
  #   resources :transactions
  # end

  # resources :statements, only: [:index, :create, :new]

  resources :users do
    resources :statements do
      resources :transactions
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/statement.rb
class Statement < ApplicationRecord
    belongs_to :user
    has_many :transactions, dependent: :destroy
    validates :title, presence: true

    def income_expense_ratio
        if !transactions.where(transaction_type: 'debit').empty?
            debits = transactions.where(transaction_type: 'debit').sum(:amount)
        else
            debits = 0
        end
        if !transactions.where(transaction_type: 'credit').empty?
            credits = transactions.where(transaction_type: 'credit').sum(:amount)
        else
            return nil
        end
        return (debits / credits.to_f).round(2)
    end

    def disposable_income
        if !transactions.where(transaction_type: 'credit').empty?
            credits = transactions.where(transaction_type: 'credit').sum(:amount)
        else
            return nil
        end
        if !transactions.where(transaction_type: 'debit').empty?
            debits = transactions.where(transaction_type: 'debit').sum(:amount)
        else
            debits = 0
        end
        return (credits - debits)
    end

    def income_expense_rating
        ratio = income_expense_ratio
        return "N/A" if ratio.nil?
        if ratio < 0.1
            return "A"
        elsif ratio > 0.1 && ratio < 0.3
            return "B"
        elsif ratio > 0.3 && ratio < 0.5
            return "C"
        else
            return "D"
        end
    end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :statement
    VALID_TRANSACTION_TYPES = ['credit', 'debit']

    validates :transaction_type, inclusion: { in: VALID_TRANSACTION_TYPES }
    validates :amount, presence: true, numericality: { greater_than: 0 }
    validates :transaction_type, presence: true
    validates :settled_timestamp, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :statements, dependent: :destroy

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  def index
    @statements = Statement.all
  end

  def show
    @statement = Statement.find(params[:id])
  end

  def new
    @statement = Statement.new
  end

  def create
    puts params.inspect
    puts "----------------"
    puts statement_params.inspect
    @statement = Statement.new(statement_params)
    if @statement.save
      redirect_to @statement, notice: 'Statement created successfully'
    else
      puts @statement.errors.full_messages
      # render json: { success: false, errors: @statement.errors.full_messages }, 
      render :new, status: :unprocessable_entity
    end
  end


  def edit
    @statement = Statement.find(params[:id])
  end
  def update
    @statement = Statement.find(params[:id])

    if @statement.update(statement_params)
      redirect_to @statement
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @statement = Statement.find(params[:id])
    @statement.destroy

    redirect_to statements_path, status: :see_other
  end

  private

  def statement_params
    params.require(:statement).permit(:title)
  end
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    def create
        @statement = Statement.find(params[:statement_id])
        @transaction = @statement.transactions.new(transaction_params)
        if !@transaction.valid?
            @transaction_amount_errors = @transaction.errors.full_messages_for(:amount)
            @transaction_transaction_type_errors = @transaction.errors.full_messages_for(:transaction_type)
            @transaction_settled_timestamp_errors = @transaction.errors.full_messages_for(:settled_timestamp)
        end
        if @transaction.save
            redirect_to statement_path(@statement)
        else
            render 'statements/show', status: :unprocessable_entity
        end
      end

      def transaction_params
        params.require(:transaction).permit(:amount, :transaction_type, :settled_timestamp)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
    end
  
    def show
      @user = User.find(params[:id])
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to @user, notice: 'User created successfully'
      else
        puts @user.errors.full_messages
        render :new, status: :unprocessable_entity
      end
    end
  
  
    def edit
      @user = User.find(params[:id])
    end
    def update
      @user = User.find(params[:id])
  
      if @user.update(user_params)
        redirect_to @user
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @user = User.find(params[:id])
      @user.destroy
  
      redirect_to users_path, status: :see_other
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email)
    end
    
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Income Expenditure App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= link_to "Statements", statements_path %>

app/views/statements/edit.html.erb
<h1>Edit Statement</h1>

<%= form_with model: @statement do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% @statement.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/statements/index.html.erb
<h1>Statements</h1

<ul>
  <% @statements.each do |statement| %>
    <li>
      <%= link_to statement.title, statement %>
    </li>
  <% end %>
</ul>

<%= link_to "New Statement", new_statement_path %>
  

app/views/statements/new.html.erb
<h1>New Statement</h1>

<%= form_with model: @statement do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @statement.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/statements/show.html.erb
<h1><%= @statement.title %></h1>

<ul>
<li><%= link_to "Edit", edit_statement_path(@statement) %></li>
<li><%= link_to "Statements", statements_path %></li>

<h2>Transactions</h2>
<% @statement.transactions.each do |transaction| %>
  <div style="display: flex; justify-content: space-between; margin-bottom: 10px;">
    <span><strong>Amount:</strong> <%= transaction.amount %></span>
    <span><strong>Transaction Type:</strong> <%= transaction.transaction_type %></span>
    <span><strong>Transaction Date:</strong> <%= transaction.settled_timestamp %></span>
  </div>
<% end %>

<h2>Income Expense Rating: <%= @statement.income_expense_rating %></h2>
<h2>Disposable Income: <%= @statement.disposable_income %></h2>
<h2>Add a transaction:</h2>
<%= form_with model: [ @statement, @statement.transactions.build ] do |form| %>
  <p>
    <%= form.label :amount %><br>
    <%= form.text_field :amount %>
    <% if @transaction_amount_errors.present? %>
            <div class="errors">
           <% @transaction_amount_errors.each do |error| %>
              <p class="error-message" style="color: darkred;"><%= error %></p>
            <% end %>
            </div>
    <% end %>
  </p>
  <p>
    <%= form.label :transaction_type %><br>
    <%= form.select :transaction_type, ['credit', 'debit'], prompt: 'Select transaction type' %>
    <% if @transaction_transaction_type_errors.present? %>
            <div class="errors">
           <% @transaction_transaction_type_errors.each do |error| %>
              <p class="error-message" style="color: darkred;"><%= error %></p>
            <% end %>
            </div>
    <% end %>
  </p>
  <p>
    <%= form.label :settled_timestamp, "Transaction Date" %><br>
    <%= form.datetime_local_field :settled_timestamp, value: Time.current.strftime("%Y-%m-%dT%H:%M") %>
    <% if @transaction_settled_timestamp_errors.present? %>
            <div class="errors">
           <% @transaction_settled_timestamp_errors.each do |error| %>
              <p class="error-message" style="color: darkred;"><%= error %></p>
            <% end %>
            </div>
    <% end %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= link_to "New User", new_user_path %>
  

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>User</h1>
<h1><%= @user.name %></h1>


<ul>
<li><%= link_to "Edit", edit_user_path(@user) %></li>


<h2>Statements</h2>
<% @user.statements.each do |statement| %>
  <div style="display: flex; justify-content: space-between; margin-bottom: 10px;">
    <span><strong>Title:</strong> <%= statement.title %></span>
    <span><strong>Created At:</strong> <%= statement.created_at %></span>
    <span><strong>Updated At:</strong> <%= statement.updated_at %></span>
  </div>
<% end %>

<%= link_to "New Statement", new_statement_path %>